apiVersion: apps/v1
kind: Deployment
metadata:
    name: portfolio-deployment
    namespace: default
spec:
    replicas: 3
    selector:
        matchLabels:
            app: portfolio
    template:
        metadata:
            labels:
                app: portfolio
        spec:
            containers:
                - name: portfolio
                  image: mehdixlabetix/portfolio:v1.0.0
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: portfolio-entrypoint
    namespace: default
spec:
    type: NodePort
    selector:
        app: portfolio
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30001
